version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/src:/usr/src/frontend/src
    ports:
      - '3000:3000'
    expose:
      - 3000
    depends_on:
      - backend
  backend:
    build: ./CourseWork
    container_name: backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_HOST: "${DATABASE_HOST}"
      ENV: "${ENV}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./CourseWork:/backend
    ports:
      - '8000:8000'
    expose:
      - 8000
